### ISSUE TITLE
CSIS Acceptance Test by CEDEX

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-technical-validation#85]
@MPerelli As announced [here](https://github.com/clarity-h2020/csis-technical-validation/issues/1), we now start with the CSIS Acceptance Tests.

Please read the [Acceptance Test Specification](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification) and follow the 11 steps in the **Walkthrough** section to test the [public BETA of CSIS](https://csis.myclimateservice.eu/).

Please report any problems or bugs according to the instructions in the **Giving Feedback** section.

If you have further questions regarding the general test process, please contact @therter and @p-a-s-c-a-l

**Comment by p-a-s-c-a-l** [comment]
Have you encountered any problems/bugs?

**Comment by MPerelli** [comment]
Hi Pascal,

I am sorry because I probably missed the previous email, aproximately two weeks ago, you invited me to access to h2020.

Could you forward me this email again?

Thank you very much.

Regards.
Marcos Perelli
Centro de Estudios del Transporte (CEDEX)
Autovía de Colmenar Viejo km 18,2
28760 Madrid
Tel.: 913357821 - E-mail: Marcos.Perelli@cedex.es<mailto:Marcos.Perelli@cedex.es>
 [Logo MITMA CET CEDEX 2020]

De: Pascal Dihé [mailto:notifications@github.com]
Enviado el: lunes, 27 de julio de 2020 10:06
Para: clarity-h2020/csis-technical-validation <csis-technical-validation@noreply.github.com>
CC: Marcos Perelli Botello <Marcos.Perelli@cedex.es>; Mention <mention@noreply.github.com>
Asunto: Re: [clarity-h2020/csis-technical-validation] CSIS Acceptance Test by CEDEX (#85)


Have you encountered any problems/bugs?

**Comment by p-a-s-c-a-l** [comment]
> Could you forward me this email again?

[Here](https://github.com/clarity-h2020/csis-technical-validation/issues/85#issue-655885094) is the invitation to tests CSIS.
